version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    env_file:
      - .env.prod
    container_name: quest
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    container_name: postgres-db
    image: postgres:12.2-alpine
    env_file:
      - .env.prod
    volumes:
      - ./pgdata:/var/lib/postgresql/data
